<?php
return array(
	'en'=>array(
		'Home'=>'Home',
		'PV Plant List'=>'PV Plant List',
		'Open Viewer'=>'Open Viewer',
		'Add Site'=>'Add Site',
		'Edit Site'=>'Edit Site',
		'ID'=>'ID',
		'Status'=>'Status',
		'Sid'=>'Sid',
		'Site Name'=>'Site Name',
		'User'=>'User',
		'Installer'=>'Installer',
		'Gateway SN'=>'Gateway SN',
		'Register Date'=>'Register Date',
		'Commission Time'=>'Commission Time',
		'Last Update'=>'Last Update',
		'nOrder'=>'nOrder'
		),
	'ja'=>array(
		'Home'=>'ホーム画面',
		'PV Plant List'=>'発電所一覧',
		'Open Viewer'=>'ビューアーへ',
		'Add Site'=>'追加',
		'Edit Site'=>'編集',
		'ID'=>'ID',
		'Status'=>'状態',
		'Sid'=>'システムID',
		'Site Name'=>'発電所名',
		'User'=>'ユーザー',
		'Installer'=>'事業者名',
		'Gateway SN'=>'ゲートウェイ製造番号',
		'Register Date'=>'追加日',
		'Commission Time'=>'通信日',
		'Last Update'=>'最終更新日',
		'nOrder'=>'排序'
		),
	'zh'=>array(
		'Home'=>'主页',
		'PV Plant List'=>'电站列表',
		'Open Viewer'=>'查看网关',
		'Add Site'=>'添加新网关',
		'Edit Site'=>'修改网关',
		'ID'=>'序号',
		'Status'=>'状态',
		'Sid'=>'电站ID',
		'Site Name'=>'电站名',
		'User'=>'用户名',
		'Installer'=>'安装商',
		'Gateway SN'=>'网关号',
		'Register Date'=>'注册日期',
		'Commission Time'=>'提交日期',
		'Last Update'=>'更新日期',
		'nOrder'=>'排序'
	),
	'de'=>array(
		'Home'            =>'Startseite',
		'PV Plant List'   =>'PV Anlagen Liste',
		'Open Viewer'     =>'Öffne Ansicht',
		'Add Site'        =>'Standort Hinzufügen',
		'Edit Site'       =>'Standort Bearbeiten',
		'ID'              =>'ID',
		'Status'          =>'Status',
		'Sid'             =>'SID',
		'Site Name'       =>'Standort Name',
		'User'            =>'Benutzer',
		'Installer'       =>'Installateur',
		'Gateway SN'      =>'Gateway Seriennummer',
		'Register Date'   =>'Registrier Datum',
		'Commission Time' =>'Errichtungs Datum',
		'Last Update'     =>'Letzte Aktualisierung',
		'nOrder'=>'nOrder'
	),
	'fr'=>array(
		'Home'=>'Page d’accueil',
		'PV Plant List'=>'Liste des sites photovoltaïques',
		'Open Viewer'=>'Visualiser',
		'Add Site'=>'Ajouter un site',
		'Edit Site'=>'Editer le site',
		'ID'=>'ID',
		'Status'=>'Statut',
		'Sid'=>'Sid',
		'Site Name'=>'Nom du site',
		'User'=>'Identifiant',
		'Installer'=>'Installateur',
		'Gateway SN'=>'No de Série de la Passerelle',
		'Register Date'=>'Date d’enregistrement',
		'Commission Time'=>'Date de mise en service',
		'Last Update'=>'Dernière mise à jour',
		'nOrder'=>'nOrder'
	),
	'es'=>array(
		'Home'=>'Home',
		'PV Plant List'=>'PV Plant List',
		'Open Viewer'=>'Open Viewer',
		'Add Site'=>'Add Site',
		'Edit Site'=>'Edit Site',
		'ID'=>'ID',
		'Status'=>'Status',
		'Sid'=>'Sid',
		'Site Name'=>'Site Name',
		'User'=>'User',
		'Installer'=>'Installer',
		'Gateway SN'=>'Gateway SN',
		'Register Date'=>'Register Date',
		'Commission Time'=>'Commission Time',
		'Last Update'=>'Last Update',
		'nOrder'=>'nOrder'
	)


)


?>